# 공간데이터

- 공공공지: 사유지가 아닌 국공유지로 향후에 발생할 수 있는 공공용도의 토지이용에 대응할 수 있다 -> 제외

In [1]:
import pandas as pd
pd.options.display.float_format = '{:.8f}'.format

gis_data = pd.read_csv('data/한국토지주택공사_공간시설 현황정보_20220802.csv',encoding='cp949')
gis_data = gis_data[gis_data['시도']=='서울특별시']


# 공원
gongwon = gis_data[gis_data['중분류'].isin(['(기존)도시자연공원','근린공원','어린이공원','소공원','역사공원','수변공원','묘지공원','체육공원','문화공원'])]
gongwon.drop_duplicates(keep='first', inplace=True)
final_gongwon = pd.DataFrame(gongwon.groupby(['시군구','읍면동']).agg({'읍면동':"count", '결정면적':"mean"}).rename(columns={'읍면동': '공원_개수', '결정면적': '공원_면적'})).reset_index()

# 녹지
nokji = gis_data[gis_data['중분류'].isin(['완충녹지','경관녹지','연결녹지'])]
nokji.drop_duplicates(keep='first', inplace=True)
final_nokji = pd.DataFrame(nokji.groupby(['시군구','읍면동'], group_keys=False).agg({'읍면동':"count", '결정면적':"mean"}).rename(columns={'읍면동': '녹지_개수', '결정면적': '녹지_면적'})).reset_index()

C:\Users\user\AppData\Local\Temp\ipykernel_3752\4074007256.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gongwon.drop_duplicates(keep='first', inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_3752\4074007256.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nokji.drop_duplicates(keep='first', inplace=True)

In [2]:
gis_data

,시도,시군구,대분류,중분류,세분류,시설명,읍면동,리,산,본,부,위치,결정면적,집행면적,미집행면적
0,서울특별시,서울특별시,공원,(기존)도시자연공원,NaN,관악산,신림동,NaN,산,94.00000000,2.00000000,관악구 봉천동 1586-17일대(신림 산94),12376211,2788513,9587698
1,서울특별시,서울특별시,공원,(기존)도시자연공원,NaN,남산,회현동1가,NaN,산,1.00000000,NaN,중구 회현1가 산1일대,1786508,433380,1353128
2,서울특별시,서울특별시,공원,(기존)도시자연공원,NaN,대모산,일원동,NaN,산,52.00000000,1.00000000,강남구 일원동 산52-1일대,5029660,1630423,3399237
3,서울특별시,서울특별시,공원,(기존)도시자연공원,NaN,봉산,갈현동,NaN,NaN,136.00000000,1.00000000,은평구 갈현동 136-1일대,1511198,797247,713951
4,서울특별시,서울특별시,공원,(기존)도시자연공원,NaN,북악산,부암동,NaN,산,1.00000000,1.00000000,종로구 부암동 성북구 성북동,1928680,1724205,204475
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4312,서울특별시,강동구,공공공지,공공공지,NaN,공공공지,암사동,NaN,NaN,116.00000000,59.00000000,암사동 116-59일대,297,297,0
4313,서울특별시,강동구,공공공지,공공공지,NaN,공공공지,둔촌동,NaN,NaN,211.00000000,NaN,둔촌동 211 일대,2286,2286,0
4314,서울특별시,강동구,공공공지,공공공지,NaN,공공공지,암사동,NaN,NaN,166.00000000,20.00000000,암사동 166-20일대,369,369,0
4315,서울특별시,강동구,공공공지,공공공지,NaN,공공공지,둔촌동,NaN,산,88.00000000,NaN,둔촌동 산88 일대,1627,1627,0
4316,서울특별시,강동구,공공공지,공공공지,NaN,공공공지,암사동,NaN,NaN,116.00000000,13.00000000,암사동 116-13일대,72,72,0

In [3]:
final_gongwon

     시군구  읍면동  공원_개수           공원_면적
0    강남구  개포동     17  30029.70588235
1    강남구  논현동      8   4968.87500000
2    강남구  대치동      6  10443.16666667
3    강남구  도곡동      7  76966.28571429
4    강남구  삼성동      5  64422.20000000
..   ...  ...    ...             ...
325  중랑구  면목동     21   1383.09523810
326  중랑구   묵동      9 109626.44444444
327  중랑구  상봉동      4   1142.00000000
328  중랑구  신내동     10  10836.50000000
329  중랑구  중화동      5    967.80000000

[330 rows x 4 columns]

In [4]:
final_nokji

     시군구  읍면동  녹지_개수         녹지_면적
0    강남구  개포동      3 5607.66666667
1    강남구  논현동      3 3357.66666667
2    강남구  도곡동      2  877.00000000
3    강남구  세곡동      9 2365.33333333
4    강남구  수서동      6 9579.16666667
..   ...  ...    ...           ...
177  중랑구  면목동      1  691.00000000
178  중랑구   묵동      8  814.25000000
179  중랑구  상봉동      1  800.00000000
180  중랑구  신내동     28 5329.53571429
181  중랑구  중화동      5 4092.20000000

[182 rows x 4 columns]

### 법정동코드

In [5]:
import pandas as pd
법정동코드 = pd.read_excel('data/한국행정구역분류_정제.xlsx',sheet_name='법정동')

In [6]:
법정동코드

        시도  시군구  법정동       법정동코드
0    서울특별시  종로구  청운동  1111010100
1    서울특별시  종로구  신교동  1111010200
2    서울특별시  종로구  궁정동  1111010300
3    서울특별시  종로구  효자동  1111010400
4    서울특별시  종로구  창성동  1111010500
..     ...  ...  ...         ...
462  서울특별시  강동구  암사동  1174010700
463  서울특별시  강동구  천호동  1174010900
464  서울특별시  강동구  성내동  1174010800
465  서울특별시  강동구   길동  1174010500
466  서울특별시  강동구  둔촌동  1174010600

[467 rows x 4 columns]

In [10]:
# 데이터프레임 합치기
# 공원
final_gis = pd.merge(법정동코드,final_gongwon, left_on=['시군구','법정동'],right_on=['시군구','읍면동'], how='left')
final_gis.drop(columns='읍면동', inplace = True)
# 녹지
final_gis = pd.merge(final_gis,final_nokji, left_on=['시군구','법정동'],right_on=['시군구','읍면동'], how='left')
final_gis.drop(columns='읍면동', inplace = True)

# nan값 채우기
final_gis.fillna(0, inplace=True)

In [11]:
final_gis

,시도,시군구,법정동,법정동코드,공원_개수,공원_면적,녹지_개수,녹지_면적
0,서울특별시,종로구,청운동,1111010100,0.00000000,0.00000000,0.00000000,0.00000000
1,서울특별시,종로구,신교동,1111010200,0.00000000,0.00000000,0.00000000,0.00000000
2,서울특별시,종로구,궁정동,1111010300,0.00000000,0.00000000,0.00000000,0.00000000
3,서울특별시,종로구,효자동,1111010400,0.00000000,0.00000000,0.00000000,0.00000000
4,서울특별시,종로구,창성동,1111010500,0.00000000,0.00000000,0.00000000,0.00000000
...,...,...,...,...,...,...,...,...
462,서울특별시,강동구,암사동,1174010700,9.00000000,14241.22222222,2.00000000,1745.00000000
463,서울특별시,강동구,천호동,1174010900,11.00000000,4258.72727273,1.00000000,2190.00000000
464,서울특별시,강동구,성내동,1174010800,8.00000000,2583.00000000,0.00000000,0.00000000
465,서울특별시,강동구,길동,1174010500,3.00000000,995.33333333,0.00000000,0.00000000
466,서울특별시,강동구,둔촌동,1174010600,3.00000000,13811.00000000,0.00000000,0.00000000

# 공시지가 - 데이터 구해서 추후 다시 하기로 함

- 20022년

In [91]:
df=pd.read_table('/data/E/서울시 번지별 공시지가 데이터 2022/TB_O_LANDVAL_2022.txt', encoding='UTF-8', sep=',', quotechar='`')

<ipython-input-91-b9341d3fd826>:1: DtypeWarning: Columns (0,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_table('C:/Users/suyeo/Desktop/나는 지우개/2.대외활동/공모전/서울빅데이터캠퍼스/data/E/서울시 번지별 공시지가 데이터 2022/TB_O_LANDVAL_2022.txt', encoding='UTF-8', sep=',', quotechar='`')

In [96]:
df = df[['YEAR','BASE_MON','JIGA','BJDONG_CD']]
df_jiga=df.groupby(['YEAR','BASE_MON','BJDONG_CD']).mean()

In [97]:
df_jiga

                              JIGA
YEAR BASE_MON BJDONG_CD
2022 1        10100     5010340.11
              10200     4064146.78
              10300     3456370.64
              10400     5109965.51
              10500     4935083.86
...                            ...
              18300     2486042.27
              18400     1617440.69
              18500     2270606.74
              18600     2337544.69
              18700     2781223.62

[87 rows x 1 columns]

In [ ]:
df_jiga.to_csv('법정동별_공시지가.csv',encoding='cp949')

- 2019년

In [111]:
jiga_2019 = pd.read_csv('data/서울시 번지별 공시지가 공간데이터 2019.csv',encoding='cp949')

<ipython-input-111-9ad98aff61e9>:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  jiga_2019 = pd.read_csv('data/서울시 번지별 공시지가 공간데이터 2019.csv',encoding='cp949')

In [118]:
# 산
jiga_2019[jiga_2019['BJDONG_CD']==2]

        BASE_MON     JIGA  BJDONG_CD
727       201901    59600          2
728       201901  1524000          2
729       201901  4070000          2
730       201901    56100          2
731       201901    55000          2
...          ...      ...        ...
912548    201901   318000          2
912549    201901   313000          2
912550    201901   319000          2
912551    201901   322000          2
912552    201901   369300          2

[15547 rows x 3 columns]

In [114]:
jiga_2019 = jiga_2019[['BASE_MON','JIGA','BJDONG_CD']]
final_jiga_2019=jiga_2019.groupby(['BASE_MON','BJDONG_CD']).mean().reset_index()

final_jiga = pd.merge(df_jiga,final_jiga_2019,on='BJDONG_CD',how='left')
final_jiga.rename(columns = {'BJDONG_CD':'법정동코드','JIGA_x':'공시지가_2022','JIGA_y':'공시지가_2019'},inplace=True)

In [127]:
final_jiga = pd.merge(법정동코드,final_jiga, on='법정동코드', how='left')
final_jiga

      법정동코드 시군구명   법정동명  공시지가_2022  공시지가_2019
0     10300  강동구    상일동 3456370.64 2720782.99
1     10300  강동구    상일동 3456370.64 2720782.99
2     10300  성북구    돈암동 3456370.64 2720782.99
3     11200  구로구     항동 6400424.20 5153816.81
4     10200  강북구     번동 4064146.78 3195176.17
...     ...  ...    ...        ...        ...
2347  91100  동작구   사당3동        NaN        NaN
2348  91200  동작구   사당4동        NaN        NaN
2349  91300  동작구  신대방1동        NaN        NaN
2350  91400  동작구  신대방2동        NaN        NaN
2351  90100  종로구   창신1동        NaN        NaN

[2352 rows x 5 columns]

In [130]:
final_jiga.to_csv('final_jiga.csv',encoding='cp949')

# 저소득층

In [92]:
저소득층 = pd.read_csv('data/SE_FN_CRD_STAT_H_DONG.csv',encoding='cp949')
저소득층=저소득층[['DO_NM','CT_NM','H_DNG_NM','total']]
저소득층_비율 = pd.DataFrame(저소득층.groupby(['CT_NM','H_DNG_NM']).agg({'total':"mean"})).reset_index().rename(columns={'CT_NM':'시군구','H_DNG_NM':'행정동명','total': '저소득층_비율'})

In [ ]:
저소득층_비율

     시군구  행정동명    저소득층_비율
0    강남구  개포1동 0.00136372
1    강남구  개포2동 0.00270010
2    강남구  개포4동 0.00210645
3    강남구  논현1동 0.00334462
4    강남구  논현2동 0.00270363
..   ...   ...        ...
421  중랑구  상봉2동 0.00222524
422  중랑구  신내1동 0.00354809
423  중랑구  신내2동 0.00247722
424  중랑구  중화1동 0.00194650
425  중랑구  중화2동 0.00305471

[426 rows x 3 columns]

In [ ]:
행정동코드 = pd.read_excel('data/한국행정구역분류_정제.xlsx',sheet_name='행정동')
df_행정동코드=행정동코드[['시군구','행정구역명','행정기관코드']].rename(columns={'행정구역명':'행정동명'})
final_저소득층=pd.merge(df_행정동코드,저소득층_비율)

final_저소득층.to_csv('전체_중_저소득층_비율.csv',encoding='cp949',index=False)

### 2019자료땜에 행정동이 424개라 두 개는 기존값 분배

In [2]:
import pandas as pd
저소득층_비율 = pd.read_csv('행정동별_저소득층_거주비율.csv',encoding='cp949')
저소득층_비율

     시군구  행정동명   저소득층_비율
0    강남구  개포1동  0.001364
1    강남구  개포2동  0.002700
2    강남구  개포4동  0.002106
3    강남구  논현1동  0.003345
4    강남구  논현2동  0.002704
..   ...   ...       ...
421  중랑구  상봉2동  0.002225
422  중랑구  신내1동  0.003548
423  중랑구  신내2동  0.002477
424  중랑구  중화1동  0.001946
425  중랑구  중화2동  0.003055

[426 rows x 3 columns]

In [3]:
저소득층_비율['저소득층_비율'].sum()

0.99999998

In [14]:
import pandas as pd
행정동코드 = pd.read_csv('행정동.csv',encoding='cp949')

In [15]:
df = pd.merge(행정동코드,저소득층_비율, left_on=['시군구','행정동'], right_on=['시군구','행정동명'],how='outer')
df

     시군구    행정동    행정동코드   행정동명   저소득층_비율
0    종로구  청운효자동  1101072  청운효자동  0.001238
1    종로구    사직동  1101053    사직동  0.000936
2    종로구    삼청동  1101054    삼청동  0.000247
3    종로구    부암동  1101055    부암동  0.000983
4    종로구    평창동  1101056    평창동  0.001624
..   ...    ...      ...    ...       ...
421  강동구   성내2동  1125066   성내2동  0.002767
422  강동구   성내3동  1125067   성내3동  0.002401
423  강동구     길동  1125074     길동  0.005080
424  강동구   둔촌1동  1125070   둔촌1동  0.001282
425  강동구   둔촌2동  1125071   둔촌2동  0.001282

[426 rows x 5 columns]

In [16]:
df[df['행정동코드'].isna()]

Empty DataFrame
Columns: [시군구, 행정동, 행정동코드, 행정동명, 저소득층_비율]
Index: []

In [17]:
df[df['저소득층_비율'].isna()]

Empty DataFrame
Columns: [시군구, 행정동, 행정동코드, 행정동명, 저소득층_비율]
Index: []

In [19]:
df = df[['시군구','행정동','행정동코드','저소득층_비율']]

In [20]:
df.to_csv('행정동_저소득가구_비율.csv',encoding='cp949',index=False)