# 버스, 지하철

In [122]:
import pandas as pd
df = pd.read_csv('최종데이터/버스,지하철 결합 격자.csv',encoding='cp949')
df.drop('left',axis=1,inplace=True)
df.drop('top',axis=1,inplace=True)
df.drop('right',axis=1,inplace=True)
df.drop('bottom',axis=1,inplace=True)

In [123]:
df['버스'].fillna(0,inplace=True)
df['지하철'].fillna(0,inplace=True)

In [124]:
df

          시도  시군구  행정동    행정동코드     법정동코드  법정동   grid            버스  지하철
0      서울특별시  종로구  사직동  1101053  11110109  누상동      1      0.000000  0.0
1      서울특별시  종로구  사직동  1101053  11110115  사직동      2  10007.452254  0.0
2      서울특별시  종로구  사직동  1101053  11110115  사직동      3   9824.109813  0.0
3      서울특별시  종로구  사직동  1101053  11110115  사직동      4     32.558804  0.0
4      서울특별시  종로구  사직동  1101053  11110109  누상동      5      0.000000  0.0
...      ...  ...  ...      ...       ...  ...    ...           ...  ...
74999  서울특별시  강동구  강일동  1125075  11740110  강일동  75000      0.000000  0.0
75000  서울특별시  강동구  강일동  1125075  11740110  강일동  75001      0.000000  0.0
75001  서울특별시  강동구  강일동  1125075  11740110  강일동  75002   2306.248398  0.0
75002  서울특별시  강동구  강일동  1125075  11740110  강일동  75003      0.000000  0.0
75003  서울특별시  강동구  강일동  1125075  11740110  강일동  75004      0.000000  0.0

[75004 rows x 9 columns]

# 재생사업

In [125]:
재생 = pd.read_excel('최종데이터/도시재생_개수.xlsx').rename(columns={'동분류위_3':'행정동코드'})
df_재생 = 재생.groupby('행정동코드').sum().reset_index()

df = pd.merge(df,df_재생,how='left',on='행정동코드').rename(columns={'도시재생사':'도시재생사업수'})
df['도시재생사업수'].fillna(0,inplace=True)
df.drop('id',axis=1,inplace=True)

In [126]:
df

,시도,시군구,행정동,행정동코드,법정동코드,법정동,grid,버스,지하철,도시재생사업수
0,서울특별시,종로구,사직동,1101053,11110109,누상동,1,0.000000,0.0,2.0
1,서울특별시,종로구,사직동,1101053,11110115,사직동,2,10007.452254,0.0,2.0
2,서울특별시,종로구,사직동,1101053,11110115,사직동,3,9824.109813,0.0,2.0
3,서울특별시,종로구,사직동,1101053,11110115,사직동,4,32.558804,0.0,2.0
4,서울특별시,종로구,사직동,1101053,11110109,누상동,5,0.000000,0.0,2.0
...,...,...,...,...,...,...,...,...,...,...
74999,서울특별시,강동구,강일동,1125075,11740110,강일동,75000,0.000000,0.0,0.0
75000,서울특별시,강동구,강일동,1125075,11740110,강일동,75001,0.000000,0.0,0.0
75001,서울특별시,강동구,강일동,1125075,11740110,강일동,75002,2306.248398,0.0,0.0
75002,서울특별시,강동구,강일동,1125075,11740110,강일동,75003,0.000000,0.0,0.0
75003,서울특별시,강동구,강일동,1125075,11740110,강일동,75004,0.000000,0.0,0.0

# 소득 및 인구

In [127]:
a = pd.read_csv('최종데이터/행정동_기초수급자인구밀도.csv',encoding='cp949')[['시군구','행정동','인구밀도 (인원 수 / 면적 (k㎡))']]
b = pd.read_csv('최종데이터/행정동_저소득가구_비율.csv',encoding='cp949')
c = pd.read_csv('최종데이터/행정동_평균생활인구수(야간).csv',encoding='cp949')[['시군구','행정동','행정동코드','행정동별_평균생활인구수']].rename(columns={'행정동별_평균생활인구수':'야간생활인구'})
d = pd.read_csv('최종데이터/행정동_평균생활인구수(주간).csv',encoding='cp949')[['시군구','행정동','행정동코드','행정동별_평균생활인구수']].rename(columns={'행정동별_평균생활인구수':'주간생활인구'})
e = pd.read_csv('최종데이터/행정동_평균생활인구수(주야간).csv',encoding='cp949')[['시군구','행정동명','행정동코드','행정동별_평균생활인구수_합계']].rename(columns={'행정동명':'행정동','행정동별_평균생활인구수_합계':'총생활인구'})
                
a1 = pd.merge(a,b)
c1 = pd.merge(c,d)
e1 = pd.merge(c1,e,on='행정동코드')

df_소득인구 = pd.merge(a1,e1,on='행정동코드',how='outer')[['행정동코드','인구밀도 (인원 수 / 면적 (k㎡))','저소득층_비율','주간생활인구','야간생활인구','총생활인구']]

In [128]:
df = pd.merge(df,df_소득인구,how='left',on='행정동코드')

In [129]:
df

,시도,시군구,행정동,행정동코드,법정동코드,법정동,grid,버스,지하철,도시재생사업수,인구밀도 (인원 수 / 면적 (k㎡)),저소득층_비율,주간생활인구,야간생활인구,총생활인구
0,서울특별시,종로구,사직동,1101053,11110109,누상동,1,0.000000,0.0,2.0,101.626016,0.000936,36892.79667,17266.69524,54159.49191
1,서울특별시,종로구,사직동,1101053,11110115,사직동,2,10007.452254,0.0,2.0,101.626016,0.000936,36892.79667,17266.69524,54159.49191
2,서울특별시,종로구,사직동,1101053,11110115,사직동,3,9824.109813,0.0,2.0,101.626016,0.000936,36892.79667,17266.69524,54159.49191
3,서울특별시,종로구,사직동,1101053,11110115,사직동,4,32.558804,0.0,2.0,101.626016,0.000936,36892.79667,17266.69524,54159.49191
4,서울특별시,종로구,사직동,1101053,11110109,누상동,5,0.000000,0.0,2.0,101.626016,0.000936,36892.79667,17266.69524,54159.49191
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74999,서울특별시,강동구,강일동,1125075,11740110,강일동,75000,0.000000,0.0,0.0,1032.258065,0.002861,46080.80333,52339.57143,98420.37476
75000,서울특별시,강동구,강일동,1125075,11740110,강일동,75001,0.000000,0.0,0.0,1032.258065,0.002861,46080.80333,52339.57143,98420.37476
75001,서울특별시,강동구,강일동,1125075,11740110,강일동,75002,2306.248398,0.0,0.0,1032.258065,0.002861,46080.80333,52339.57143,98420.37476
75002,서울특별시,강동구,강일동,1125075,11740110,강일동,75003,0.000000,0.0,0.0,1032.258065,0.002861,46080.80333,52339.57143,98420.37476
75003,서울특별시,강동구,강일동,1125075,11740110,강일동,75004,0.000000,0.0,0.0,1032.258065,0.002861,46080.80333,52339.57143,98420.37476

# 미세먼지

In [130]:
a =pd.read_csv('최종데이터/행정동_초미세먼지(2021년).csv',encoding='cp949')
b =pd.read_csv('최종데이터/행정동_미세먼지(2021년).csv',encoding='cp949')
df_미세먼지 = pd.merge(a,b)[['행정기관코드','초미세먼지','미세먼지']].rename(columns={'행정기관코드':'행정동코드'})
df = pd.merge(df,df_미세먼지,how='left',on='행정동코드')

In [131]:
df

,시도,시군구,행정동,행정동코드,법정동코드,법정동,grid,버스,지하철,도시재생사업수,인구밀도 (인원 수 / 면적 (k㎡)),저소득층_비율,주간생활인구,야간생활인구,총생활인구,초미세먼지,미세먼지
0,서울특별시,종로구,사직동,1101053,11110109,누상동,1,0.000000,0.0,2.0,101.626016,0.000936,36892.79667,17266.69524,54159.49191,21,40
1,서울특별시,종로구,사직동,1101053,11110115,사직동,2,10007.452254,0.0,2.0,101.626016,0.000936,36892.79667,17266.69524,54159.49191,21,40
2,서울특별시,종로구,사직동,1101053,11110115,사직동,3,9824.109813,0.0,2.0,101.626016,0.000936,36892.79667,17266.69524,54159.49191,21,40
3,서울특별시,종로구,사직동,1101053,11110115,사직동,4,32.558804,0.0,2.0,101.626016,0.000936,36892.79667,17266.69524,54159.49191,21,40
4,서울특별시,종로구,사직동,1101053,11110109,누상동,5,0.000000,0.0,2.0,101.626016,0.000936,36892.79667,17266.69524,54159.49191,21,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74999,서울특별시,강동구,강일동,1125075,11740110,강일동,75000,0.000000,0.0,0.0,1032.258065,0.002861,46080.80333,52339.57143,98420.37476,21,39
75000,서울특별시,강동구,강일동,1125075,11740110,강일동,75001,0.000000,0.0,0.0,1032.258065,0.002861,46080.80333,52339.57143,98420.37476,21,39
75001,서울특별시,강동구,강일동,1125075,11740110,강일동,75002,2306.248398,0.0,0.0,1032.258065,0.002861,46080.80333,52339.57143,98420.37476,21,39
75002,서울특별시,강동구,강일동,1125075,11740110,강일동,75003,0.000000,0.0,0.0,1032.258065,0.002861,46080.80333,52339.57143,98420.37476,21,39
75003,서울특별시,강동구,강일동,1125075,11740110,강일동,75004,0.000000,0.0,0.0,1032.258065,0.002861,46080.80333,52339.57143,98420.37476,21,39

# 1인녹지면적

In [132]:
형평성=pd.read_csv('최종데이터/법정동_공원녹지개수.csv',encoding='cp949')[['법정동코드','1인당면적total']].rename(columns={'1인당면적total':'인당녹지면적'})

In [134]:
df = pd.merge(df,형평성,how='left',on='법정동코드')

In [135]:
df['도시재생사업수'].fillna(0,inplace=True)

In [137]:
df

,시도,시군구,행정동,행정동코드,법정동코드,법정동,grid,버스,지하철,도시재생사업수,인구밀도 (인원 수 / 면적 (k㎡)),저소득층_비율,주간생활인구,야간생활인구,총생활인구,초미세먼지,미세먼지,인당녹지면적
0,서울특별시,종로구,사직동,1101053,11110109,누상동,1,0.000000,0.0,2.0,101.626016,0.000936,36892.79667,17266.69524,54159.49191,21,40,0.000000
1,서울특별시,종로구,사직동,1101053,11110115,사직동,2,10007.452254,0.0,2.0,101.626016,0.000936,36892.79667,17266.69524,54159.49191,21,40,51.123292
2,서울특별시,종로구,사직동,1101053,11110115,사직동,3,9824.109813,0.0,2.0,101.626016,0.000936,36892.79667,17266.69524,54159.49191,21,40,51.123292
3,서울특별시,종로구,사직동,1101053,11110115,사직동,4,32.558804,0.0,2.0,101.626016,0.000936,36892.79667,17266.69524,54159.49191,21,40,51.123292
4,서울특별시,종로구,사직동,1101053,11110109,누상동,5,0.000000,0.0,2.0,101.626016,0.000936,36892.79667,17266.69524,54159.49191,21,40,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74999,서울특별시,강동구,강일동,1125075,11740110,강일동,75000,0.000000,0.0,0.0,1032.258065,0.002861,46080.80333,52339.57143,98420.37476,21,39,13.779205
75000,서울특별시,강동구,강일동,1125075,11740110,강일동,75001,0.000000,0.0,0.0,1032.258065,0.002861,46080.80333,52339.57143,98420.37476,21,39,13.779205
75001,서울특별시,강동구,강일동,1125075,11740110,강일동,75002,2306.248398,0.0,0.0,1032.258065,0.002861,46080.80333,52339.57143,98420.37476,21,39,13.779205
75002,서울특별시,강동구,강일동,1125075,11740110,강일동,75003,0.000000,0.0,0.0,1032.258065,0.002861,46080.80333,52339.57143,98420.37476,21,39,13.779205
75003,서울특별시,강동구,강일동,1125075,11740110,강일동,75004,0.000000,0.0,0.0,1032.258065,0.002861,46080.80333,52339.57143,98420.37476,21,39,13.779205

In [142]:
df['grid'] = df['grid'].astype(object)
df['행정동코드'] = df['행정동코드'].astype(object)
df['법정동코드'] = df['법정동코드'].astype(object)

In [143]:
df.corr()

,버스,지하철,도시재생사업수,인구밀도 (인원 수 / 면적 (k㎡)),저소득층_비율,주간생활인구,야간생활인구,총생활인구,초미세먼지,미세먼지,인당녹지면적
버스,1.000000,0.173116,0.009023,0.174132,-0.002789,-0.036453,-0.038908,-0.039041,-0.013802,-0.006152,-0.071672
지하철,0.173116,1.000000,0.000522,0.012456,-0.006544,0.021609,0.002706,0.014961,0.005041,0.004994,-0.021656
도시재생사업수,0.009023,0.000522,1.000000,-0.035629,-0.045451,0.088714,0.044735,0.074936,0.019670,-0.005327,0.026886
인구밀도 (인원 수 / 면적 (k㎡)),0.174132,0.012456,-0.035629,1.000000,0.180432,-0.189581,-0.038330,-0.137120,0.039533,0.023295,-0.093427
저소득층_비율,-0.002789,-0.006544,-0.045451,0.180432,1.000000,0.416472,0.717611,0.555806,0.122309,-0.139524,-0.028982
주간생활인구,-0.036453,0.021609,0.088714,-0.189581,0.416472,1.000000,0.825981,0.973997,0.136412,-0.039035,0.071543
야간생활인구,-0.038908,0.002706,0.044735,-0.038330,0.717611,0.825981,1.000000,0.932216,0.159426,-0.068607,0.027294
총생활인구,-0.039041,0.014961,0.074936,-0.137120,0.555806,0.973997,0.932216,1.000000,0.151656,-0.052636,0.056879
초미세먼지,-0.013802,0.005041,0.019670,0.039533,0.122309,0.136412,0.159426,0.151656,1.000000,0.470996,0.099221
미세먼지,-0.006152,0.004994,-0.005327,0.023295,-0.139524,-0.039035,-0.068607,-0.052636,0.470996,1.000000,0.134587
인당녹지면적,-0.071672,-0.021656,0.026886,-0.093427,-0.028982,0.071543,0.027294,0.056879,0.099221,0.134587,1.000000

In [144]:
df.to_csv('최종데이터_공시지가제외.csv',encoding='cp949',index=False)

### 주은이한테 공시지가 포함 데이터 받음

# 기온

In [2]:
import pandas as pd
df = pd.read_csv('최종데이터.csv',encoding='cp949')

In [ ]:
data=pd.read_csv('data/기온데이터.csv',encoding='cp949')
data['시군구'] = data['지점명'].map(lambda x:x+'구')

In [ ]:
final=data.groupby(['시군구']).agg({"평균기온(°C)":'mean'}).reset_index()
final.to_csv('구별기온.csv',encoding='cp949',index=False)

In [64]:
a = pd.merge(df,final, how='left')
b = pd.merge(df,a,how='left')
b.to_csv('최종데이터.csv',encoding='cp949',index=False)

# 자연요소 제거

In [1]:
import pandas as pd
df1=pd.read_csv('최종데이터/최종데이터.csv',encoding='cp949')
df2=pd.read_csv('최종데이터/후보지격자.csv',encoding='cp949')
df3=pd.read_csv('최종데이터/전체_하천격자.csv',encoding='cp949')

In [2]:
df1.head(3)

,시도,시군구,행정동,행정동코드,법정동코드,법정동,grid,버스,지하철,도시재생사업수,...,저소득층_비율,주간생활인구,야간생활인구,총생활인구,초미세먼지,미세먼지,인당녹지면적,토지공시지가평균,임야공시지가평균,총공시지가평균
0,서울특별시,종로구,사직동,1101053,11110109,누상동,1,0.000000,0.0,2,...,0.000936,36892.79667,17266.69524,54159.49191,21,40,0.000000,4099760.252,194850.0000,4051100.935
1,서울특별시,종로구,사직동,1101053,11110115,사직동,2,10007.452250,0.0,2,...,0.000936,36892.79667,17266.69524,54159.49191,21,40,51.123292,3778295.345,195318.1818,3647355.980
2,서울특별시,종로구,사직동,1101053,11110115,사직동,3,9824.109813,0.0,2,...,0.000936,36892.79667,17266.69524,54159.49191,21,40,51.123292,3778295.345,195318.1818,3647355.980

In [3]:
df2.head(3)

,시도,시군구,행정동,행정동코드,법정동코드,법정동,grid,버스,지하철,도시재생사업수,...,주간생활인구,야간생활인구,총생활인구,초미세먼지,미세먼지,인당녹지면적,토지공시지가평균,임야공시지가평균,총공시지가평균,토지유형
0,서울특별시,종로구,사직동,1101053,11110181,행촌동,12,32.851664,0.0,2,...,36892.79667,17266.69524,54159.49191,21,40,1.310124,2396871.578,0.0,2396871.578,일반
1,서울특별시,종로구,사직동,1101053,11110178,송월동,17,10007.456910,0.0,2,...,36892.79667,17266.69524,54159.49191,21,40,15.085963,3937642.857,0.0,3937642.857,일반
2,서울특별시,종로구,사직동,1101053,11110109,누상동,18,0.000000,0.0,2,...,36892.79667,17266.69524,54159.49191,21,40,0.000000,4099760.252,194850.0,4051100.935,일반

In [4]:
df3.head(3)

,시도,시군구,행정동,행정동코드,법정동코드,법정동,grid,버스,지하철,도시재생사업수,...,주간생활인구,야간생활인구,총생활인구,초미세먼지,미세먼지,인당녹지면적,토지공시지가평균,임야공시지가평균,총공시지가평균,토지유형_하천
0,서울특별시,종로구,사직동,1101053,11110119,세종로,120,0.000000,0.0,2,...,36892.796670,17266.695240,54159.49191,21,40,NaN,2.590660e+07,0.0000,2.590660e+07,하천
1,서울특별시,종로구,삼청동,1101054,11110149,원서동,312,841.520509,0.0,2,...,7484.263333,3700.411905,11184.67524,21,40,5.742824,4.690928e+06,359800.0000,4.663602e+06,하천
2,서울특별시,종로구,삼청동,1101054,11110148,계동,314,9770.415096,0.0,2,...,7484.263333,3700.411905,11184.67524,21,40,0.000000,5.404021e+06,953628.5714,5.358276e+06,하천

In [5]:
df = pd.merge(df1,df3,how='outer')

In [6]:
df_final = pd.merge(df,df2,how='outer')

In [7]:
df_final['토지유형_하천'].fillna(df_final['토지유형'],inplace=True)

In [8]:
df_final['토지유형_하천'].fillna('산,녹지',inplace=True)

In [54]:
df_final.to_csv('최종_전체데이터.csv',encoding='cp949',index=False)

In [3]:
import pandas as pd
a = pd.read_csv('최종_전체데이터.csv',encoding='cp949')

In [4]:
b = a[a['토지유형']=='일반'].reset_index(drop=True)

In [5]:
b.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30620 entries, 0 to 30619
Data columns (total 20 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   grid        30620 non-null  int64
 1   시도          30620 non-null  object
 2   시군구         30620 non-null  object
 3   행정동         30620 non-null  object
 4   행정동코드       30620 non-null  int64
 5   법정동코드       30620 non-null  int64
 6   법정동         30620 non-null  object
 7   대중교통        30620 non-null  float64
 8   도시재생사업수     30620 non-null  int64
 9   기초수급자_인구밀도  30620 non-null  float64
 10  저소득층_비율     30620 non-null  float64
 11  총생활인구       30620 non-null  float64
 12  초미세먼지       30620 non-null  int64
 13  미세먼지        30620 non-null  int64
 14  인당녹지면적      30317 non-null  float64
 15  토지공시지가평균    30620 non-null  float64
 16  임야공시지가평균    30620 non-null  float64
 17  총공시지가평균     30620 non-null  float64
 18  토지유형        30620 non-null  object
 19  평균기온(°C)    30620 non-null  float64
dtypes: float64(9), int64(6), object(5)
memory usage: 4.7+ MB

In [6]:
b = a[a['토지유형']=='일반'].reset_index(drop=True)
c = b.dropna(axis=0).reset_index(drop=True)
c.to_csv('최종_분석데이터.csv',encoding='cp949',index=False)

In [7]:
c.to_csv('최종_분석데이터.csv',encoding='cp949',index=False)

In [8]:
c

,grid,시도,시군구,행정동,행정동코드,법정동코드,법정동,대중교통,도시재생사업수,기초수급자_인구밀도,저소득층_비율,총생활인구,초미세먼지,미세먼지,인당녹지면적,토지공시지가평균,임야공시지가평균,총공시지가평균,토지유형,평균기온(°C)
0,12,서울특별시,종로구,사직동,1101053,11110181,행촌동,32.851664,2,101.626016,0.000936,54159.49191,21,40,1.310124,2396871.578,0.0000,2396871.578,일반,-2.65
1,17,서울특별시,종로구,사직동,1101053,11110178,송월동,10007.456910,2,101.626016,0.000936,54159.49191,21,40,15.085963,3937642.857,0.0000,3937642.857,일반,-2.65
2,18,서울특별시,종로구,사직동,1101053,11110109,누상동,0.000000,2,101.626016,0.000936,54159.49191,21,40,0.000000,4099760.252,194850.0000,4051100.935,일반,-2.65
3,27,서울특별시,종로구,사직동,1101053,11110115,사직동,10000.721880,2,101.626016,0.000936,54159.49191,21,40,51.123292,3778295.345,195318.1818,3647355.980,일반,-2.65
4,29,서울특별시,종로구,사직동,1101053,11110110,누하동,0.000000,2,101.626016,0.000936,54159.49191,21,40,0.000000,5636537.778,0.0000,5636537.778,일반,-2.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30312,74995,서울특별시,강동구,강일동,1125075,11740110,강일동,7621.976731,0,1032.258065,0.002861,98420.37476,21,39,13.779205,1208408.352,436105.8824,1194059.563,일반,-0.45
30313,74996,서울특별시,강동구,강일동,1125075,11740110,강일동,9832.794677,0,1032.258065,0.002861,98420.37476,21,39,13.779205,1208408.352,436105.8824,1194059.563,일반,-0.45
30314,74997,서울특별시,강동구,강일동,1125075,11740110,강일동,10007.804010,0,1032.258065,0.002861,98420.37476,21,39,13.779205,1208408.352,436105.8824,1194059.563,일반,-0.45
30315,74998,서울특별시,강동구,강일동,1125075,11740110,강일동,10007.804010,0,1032.258065,0.002861,98420.37476,21,39,13.779205,1208408.352,436105.8824,1194059.563,일반,-0.45
30316,74999,서울특별시,강동구,강일동,1125075,11740110,강일동,10007.804010,0,1032.258065,0.002861,98420.37476,21,39,13.779205,1208408.352,436105.8824,1194059.563,일반,-0.45