In [3]:
import pandas as pd
df = pd.read_csv('data/한국토지주택공사_공간시설 현황정보_20220802.csv',encoding='cp949')

In [4]:
df.head(3)

,시도,시군구,대분류,중분류,세분류,시설명,읍면동,리,산,본,부,위치,결정면적,집행면적,미집행면적
0,서울특별시,서울특별시,공원,(기존)도시자연공원,NaN,관악산,신림동,NaN,산,94.0,2.0,관악구 봉천동 1586-17일대(신림 산94),12376211,2788513,9587698
1,서울특별시,서울특별시,공원,(기존)도시자연공원,NaN,남산,회현동1가,NaN,산,1.0,NaN,중구 회현1가 산1일대,1786508,433380,1353128
2,서울특별시,서울특별시,공원,(기존)도시자연공원,NaN,대모산,일원동,NaN,산,52.0,1.0,강남구 일원동 산52-1일대,5029660,1630423,3399237

In [14]:
df_공원녹지 = df[(df.시도=='서울특별시')&(df.대분류.isin(['공원','녹지']))].groupby('시군구').agg({'결정면적':'sum'}).reset_index()

In [20]:
final_공원녹지 = df_공원녹지[df_공원녹지.시군구 != '서울특별시'].reset_index(drop=True)

In [23]:
final_공원녹지.to_csv('구별_공원녹지면적.csv',encoding='cp949',index=False)

# 만족도

In [24]:
df= pd.read_excel('data/지역+녹지+만족도_20221021174754.xlsx')

C:\Users\user\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [25]:
df

    구분별(1) 구분별(2)          항목   2018  2019  2020  2021
0      서울시     소계           계  100.0     -     -     -
1      NaN    NaN  매우 불만족 (점)    1.8   0.8   2.4   2.5
2      NaN    NaN  약간 불만족 (점)   11.5   8.5  12.8  12.8
3      NaN    NaN      보통 (점)   39.7  50.4  40.0  38.6
4      NaN    NaN   약간 만족 (점)   41.6  33.5  34.9  34.6
..     ...    ...         ...    ...   ...   ...   ...
376    NaN    NaN  약간 불만족 (점)   14.8  10.1  15.2  12.7
377    NaN    NaN      보통 (점)   40.0  49.6  42.5  44.2
378    NaN    NaN   약간 만족 (점)   36.4  33.7  29.7  30.8
379    NaN    NaN   매우 만족 (점)    2.2   6.2  11.5  10.4
380    NaN    NaN  10점 평균 (%)      -  5.88  5.88  5.88

[381 rows x 7 columns]